#!/bin/bash

LOGCMP="Initialization Sequence Completed"
TUNCMP="tun0"
LOGSTATUS=$(tail --bytes 34 /var/log/openvpn.log | head --bytes 33)
TUNSTATUS=$(ifconfig | grep tun0 | head --bytes 4)
PID=$(cat /run/openvpn/openvpn.pid)

if ps -p $PID > /dev/null 
then
  
  if [ "$LOGCMP" == "$LOGSTATUS" ]
  then
    echo -e "<span foreground='#00FF00'></span>"
  else
    echo -e "<span foreground='#FF7700'></span>"
  fi 

else

  if [ "$TUNCMP" == "$TUNSTATUS" ]
  then
    echo -e "<span foreground='#00FF00'></span>"
  else
    echo -e "<span foreground='#FF0000'></span>"
  fi

fi

